### PR TITLE
Snabb pflua integration

### PR DESCRIPTION
**Pull request by dpino**
Continuation of https://github.com/andywingo/snabbswitch/pull/3 .

### CODE REVIEW

**Comment by dpino** [comment]
Branch rebased to current master.

**Selftests**
- Packet filter test

Snabb's packet filter

``` bash
$ sudo ./snabb snsh -t apps.packet_filter.packet_filter_test
link report
6 sent on packet_filter1.output -> sink1.input (loss rate: 0%))
161 sent on source1.output -> packet_filter1.input (loss rate: 0%))
19 sent on packet_filter2.output -> sink2.input (loss rate: 0%))
43 sent on source2.output -> packet_filter2.input (loss rate: 0%))
selftest passed
link report
161 sent on source1.output -> statefull_pass1.input (loss rate: 0%))
43 sent on source2.output -> statefull_pass2.input (loss rate: 0%))
36 sent on statefull_pass2.output -> sink2.input (loss rate: 0%))
6 sent on statefull_pass1.output -> sink1.input (loss rate: 0%))
selftest failed
```

Pflua

``` bash
src $ sudo ./snabb snsh -pflua -t apps.packet_filter.packet_filter_test
link report
6 sent on packet_filter1.output -> sink1.input (loss rate: 0%))
161 sent on source1.output -> packet_filter1.input (loss rate: 0%))
19 sent on packet_filter2.output -> sink2.input (loss rate: 0%))
43 sent on source2.output -> packet_filter2.input (loss rate: 0%))
selftest passed
```
- vpws

``` bash
src $ sudo ./snabb snsh -pflua -t apps.vpn.vpws
link report
100 sent on from_uplink.output -> vpntp.uplink (loss rate: 0%))
100 sent on vpntp.uplink -> to_uplink.input (loss rate: 0%))
100 sent on vpntp.customer -> to_customer.input (loss rate: 0%))
100 sent on from_customer.output -> vpntp.customer (loss rate: 0%))
```
- ns_responder

``` bash
src $ sudo ./snabb snsh -pflua -t apps.ipv6.ns_responder
link report
161 sent on source1.output -> packet_filter.input (loss rate: 0%))
9 sent on packet_filter.output -> sink1.input (loss rate: 0%))
selftest passed
```
- nd_light

``` bash
src $ sudo ./snabb snsh -pflua -t apps.ipv6.nd_light
link report
161 sent on source1.output -> packet_filter.input (loss rate: 0%))
18 sent on packet_filter.output -> sink1.input (loss rate: 0%))
selftest passed
```

**Benchmark**
- Snabb's packet filter

``` bash
src $ sudo ./snabb snsh -t apps.packet_filter.packet_filter_benchmark
Run for 1 second ...
done
link report
161 sent on source.output -> repeater.input (loss rate: 0%))
12528915 sent on repeater.output -> packet_filter.input (loss rate: 0%))
466916 sent on packet_filter.output -> sink.input (loss rate: 0%))
```
- Pflua

``` bash
src $ sudo ./snabb snsh -pflua -t apps.packet_filter.packet_filter_benchmark
Run for 1 second ...
done
link report
161 sent on source.output -> repeater.input (loss rate: 0%))
10413690 sent on repeater.output -> packet_filter.input (loss rate: 0%))
388088 sent on packet_filter.output -> sink.input (loss rate: 0%))
```

**Comment by dpino** [comment]
There's a little issue I don't know what's the best way how to solve it.

Snabbswitch's file `syscall/linux/ffi.lua` is inclusing the C datatype `time_t` via ffi. This datatype is also included by pflua. This makes the struct to be included twice, which causes an error. Unfortunately, LuaJIT doesn't support `#ifdef`.

I solved a similar issue by defining a global "pflua" flag in Snabbswitch. This allowed me to avoid including C datatypes common between Snabbswitch and pflua. The problem here is that `syscall/linux/ffi.lua` is not a file tracked by the git repo.

What I did was to modified pflua's source code to avoid including this C datatype. This is not a feasible solution, as pflua will only work inside Snabbswitch. We could include a guard in pflua, a variable called `snabb` for instance,  to avoid including that C datatype twice, but that seems to me like a deliberately change. I don't like it much.

A possible solution could be to include this commit as a patch and the user should apply it locally. We could even make `make update-pflua` to apply this patch automatically. The file that needs to be patched is `pflua/src/pf/utils.lua`, which is a very stable file. WDYT?

**Comment by dpino** [comment]
@andywingo @lukego please, could you take a look? I think at this point the integration between snabbswitch and pflua is completed, the only thing pending is how to avoid the double inclusion of certain data structures. See comment last comment.

**Comment by wingo** [comment]
An automatically-applied patch sounds fine to me.

**Pull request closed without merging**
